UepaTicksWeb/Controllers/UepaHomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UepaTicksWeb.Models;

namespace UepaTicksWeb.Controllers
{
    public class UepaHomeController : Controller
    {


        private void CargarDropdwon()
        {
            //Este metodo es para cargar los Evento en el dropdwonlist que se presenta en la vista
            List<SelectListItem> listEventos = new()
            {
                new SelectListItem { Value = "AT", Text = "Artes y Tearo" },
                new SelectListItem { Value = "CT", Text = "Concierto" },
                new SelectListItem { Value = "CF", Text = "Conferencia" },
                new SelectListItem { Value = "Ed", Text = "Educativo" },
                new SelectListItem { Value = "Edc", Text = "Educativo" },
                new SelectListItem { Value = "Ev", Text = "Eventos" },
                new SelectListItem { Value = "Inf", Text = "Infaltil " }
            };
            ViewBag.Eventos = listEventos;
        }

        private void CargarDropdownCondicion()
        {
            List<SelectListItem> listCondicion = new()
            {
                new SelectListItem { Value = "OD", Text = "Por orden de llegada" },
                new SelectListItem { Value = "AN", Text = "Asientos numerados" }

            };
            ViewBag.Condicion = listCondicion;
        }

        [HttpGet]
        public IActionResult Index()
        {
            CargarDropdwon();
            CargarDropdownCondicion();

            return View();
        }

        [HttpPost]
        public IActionResult Index(MUepaDatos mUepaDatos)
        {
            /* ESTA ES LA VALIDACION DEL MODELO PARA AGREGAR LO A LA BASE DE DATO
            if (ModelState.IsValid)
            {
                if (Repo.Add(mUepaDatos))
                {
                    return RedirectToAction("Index");
                }
                else
                    ModelState.AddModelError(string.Empty, "Error! El Evento no fue registrado");
                return View(); 
            }
            else
                ModelState.AddModelError("Error!", "Por favor espere en línea un momento");
            return View(mUepaDatos);*/
            return View();
        }
    }

}

UepaTicksWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UepaTicksWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/newestilo.css" />
    <link rel="stylesheet" href="~/favicon.ico" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/SimpleCalendar/simple-calendar.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-4 col-md-4"></div>
                <div class="col-4 col-md-4">
                    <a href="/">
                        <img style="width:90px" class="ulogo" src="@Url.Content("~/img/uepa_tickets.svg")" />
                    </a>
                    <br />
                    <span class="hidde-xs spans" style="">Tu entrada a los grandes eventos...</span>
                </div>
                <div class="col-4 col-md-4">
                    <div class="row">
                        <div class="col-10 col-md-10">
                            <div class="float-right float-sm-right">
                                <a class="btn btn-dark buttons" asp-area="" asp-controller="UepaHome" asp-action="Index">+ Crear Evento</a>
                            </div>
                        </div>
                        <div class="col-2 col-md-2">
                            <div class="navbar icon-acceso">
                                <div class="dropdown icon-acceso">
                                    <a href="#">
                                        <svg class="material-icons icon-login icon-acceso" viewBox="0 0 24 24" xmlns=""><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 3c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm0 14.2c-2.5 0-4.71-1.28-6-3.22.03-1.99 4-3.08 6-3.08 1.99 0 5.97 1.09 6 3.08-1.29 1.94-3.5 3.22-6 3.22z"></path><path d="M0 0h24v24H0z" fill="none"></path></svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 menus-nav navbar-nav">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between barra-menus">
                    <ul class="navbar-nav flex-grow-1" style="font-size: 14px;">
                        <li>
                            <a class="nav-link uepa-link" asp-area="" asp-controller="Home" asp-action="Index">Eventos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link uepa-link" asp-area="" asp-controller="Home" asp-action="Ventas">Puntos de Ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link uepa-link" asp-area="" asp-controller="Home" asp-action="Privacy">Contactos</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav navbar-right flex-grow-1">
                        <li class="navbar-nav">
                            <a href="https://web.facebook.com/UepaTickets/" target="_blank" data-label="Facebook" rel="nofollow" class="faceboo uepa-link">
                                <i style="font-size: 20px; margin: 14px; margin-left: 485px;" class="fa-brands fa-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/uepatickets/" target="_blank" data-label="Instagran" rel="nofollow" class="instagran uepa-link">
                                <i style="font-size: 20px; margin: 14px;" class="fa-brands fa-instagram"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/uepatickets" target="_blank" data-label="Twitter" rel="nofollow" class="twitter uepa-link">
                                <i style="font-size: 20px; margin: 14px;" class="fa-brands fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.youtube.com/channel/UCxQRgn4mClqGPW6ZSFHOqvQ" target="_blank" data-label="You Tube" rel="nofollow" class="youtube uepa-link">
                                <i style="font-size: 20px; margin: 14px;" class="fa-brands fa-youtube"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://feedburner.google.com/fb/a/mailverify?uri=UepaTickets" target="_blank" data-label="RSS" rel="nofollow" class="rss uepa-link">
                                <i style="font-size: 20px; margin: 14px; float: right;" class="fa-sharp fa-solid fa-wifi"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br />
    <div class="container-footer">
        <footer class="card card-default border-top footer text-muted" style="margin: 0px 0px 6px 0px;">
            <div class="panel-body">
                <div class="row" style="max-width: 1130px; margin: 0px auto;">
                    <div class="col-md-4 col-xs-12 col-sm-4">
                        <div class="left-resp" style="text-align: justify; padding: 9px; color: #555; margin-left: -45px;">
                            "El éxito de una empresa solo se logra si se es disciplinado, si se tiene fe en el equipo de trabajo elegido y si no se toman decisiones improvisadas."
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-12 col-sm-4">
                        <div style="text-align: center;">
                            <!--DIV CON LA SECCION DE ESTABLECIMIENTO-->
                            <a href="#">
                                <img src ="~/img/logo_ccn_new.png" class="img-footer">
                            </a>
                            <a href="#">
                                <img src="~/img/smn-web-footer.jpg" class="img-footer">
                            </a>
                            <a>
                                <img src="~/img/jumbo-web-footer.jpg" class="img-footer"/>
                            </a>
                        </div>
                    </div>
                    <!--SIGUIENTE DIV CON ACCESO-->
                    <div class="col-md-4 col-xs-12 col-sm-4">
                        <!-- Columna de categorias Ejemplo: Arte y  Tearo, Conciertos, Deportes-->
                        <div class="social-icons-footer" style="max-width: 300px; right: 20px; bottom: 30px;">
                            <div class="btn-acces">
                                <a class="btn btn-xs btn-ligth btn-sm" href="/?category_name=Artes%20y%20Teatro">Artes y Teatro</a>
                                <a class="btn btn-xs btn-ligth btn-sm" href="/?category_name=Conciertos">Conciertos</a>
                                <a class="btn btn-xs btn-ligth btn-sm" href="/?category_name=Conferencia">Conferencia</a>
                                <a class="btn btn-xs btn-ligth btn-sm" href="/?category_name=Deportes">Deportes</a>
                                <a class="btn btn-xs btn-ligth btn-sm" href="/?category_name=Educativo">Educativo</a>
                                <a class="btn btn-xs btn-ligth btn-sm" href="/?category_name=Eventos">Eventos</a>
                                <a class="btn btn-xs btn-ligth btn-sm" href="/?category_name=Infantil">Infantil</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="max-width: 1130px; margin: 0px auto;">
                <div class="col-md-4 col-xs-12 col-sm-4">
                    <div class="social-icons-footer left-resp footers-icon">
                        <a href="https://web.facebook.com/UepaTickets/" target="_blank" data-label="Facebook" rel="nofollow" class="facebook ">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a href="https://www.instagram.com/uepatickets/" target="_blank" data-label="Instagran" rel="nofollow" class="instagram">
                            <i class="@*fa-brands fa-instagram*@ fa-brands fa-square-instagram"></i>
                        </a>
                        <a href="https://twitter.com/uepatickets" target="_blank" data-label="Twitter" rel="nofollow" class="twitter">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                        <a href="https://www.youtube.com/channel/UCxQRgn4mClqGPW6ZSFHOqvQ" target="_blank" data-label="YouTube" rel="nofollow" class="youtube">
                            <i class="fa-brands fa-youtube"></i>
                        </a>
                        <a href="#" target="_blank" data-label="Linkedin" rel="nofollow" class="facebook">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a href="#" target="_blank" data-label="Pinteres" rel="nofollow" class="pinteres">
                            <i class="fa-brands fa-pinterest"></i>
                        </a>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12 col-sm-4">
                    <div class="" style="text-align: center; position: relative; top: -44px;">
                        <img src="~/img/payment.png" style="max-width: 120px;">
                    </div>
                </div>
                @*<div class="col-md-4 col-xs-12 col-sm-4"></div>*@
            </div>
            <div class="panels-footer">
                <div class="row" style="max-width: 1130px; margin: 0px auto; color: #edeef0;text-align: center !important;">
                    <div class="col-md-4 col-xs-12 col-sm-4" style="left:340px; outline: none;">
                        <a href="#" style="font-size: 9px;color: #999;outline: none; text-align: center !important;" data-toggle="modal" data-target="#myModalATC">
                            <span class="btn btn-link" style="font-size: 9px; color: red; ">© 2018 <b>Uepa Tickets</b>. All rights reserved.</span>
                        </a>
                    </div>
                    <div class="col-md-4 col-xs-12 col-sm-4"></div>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/SimpleCalendar/jquery.simple-calendar.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>